version: "3.9"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: default_db
volumes:
  postgresql:
  node:
